import pdf from 'html-pdf';
import path from 'path';
import fs from 'fs';

let module;

const getBase64String = (path) => {
  try {
    const file = fs.readFileSync(path);
    return new Buffer(file).toString('base64');
  } catch (exception) {
    module.reject(exception);
  }
};

const generatePDF = ({html, filename}, promise) => {
  module = promise;
  try {
    pdf.create(html, {
      format: 'A4',
      border: {
        top: '24px',
        bottom: 0,
        left: 0,
        right: 0
      },
      zoomFactor: 0.5,
      footer: {
        height: '20px',
        contents: {
          default: '<span style="color: #ccc; font-size: 11px; float: right; padding-right: 15px">Generated by www.cvmaker.co.in</span>'
        }
      }
    }).toFile(path.join(__dirname,`../pdf/${filename}.pdf`), (error, response) => {
      if (error) {
        module.reject(error);
      } else {
        module.resolve({ filename, base64: getBase64String(response.filename) });
        fs.unlink(response.filename);
      }
    });
  } catch (exception) {
    module.reject(exception);
  }
};

export const generateComponentAsPDF = ({ html, filename }) => {
  return new Promise((resolve, reject) => {
    return generatePDF({ html, filename }, { resolve, reject });
  });
};
